version: '3.9'

services:
  database:
    image: postgres
    container_name: database_ignite
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
      - 9229:9229
    environment:
      - DB_HOST=database_application
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

  migrations:
    build:
      context: .
    command:
      [
        'npm',
        'run',
        'typeorm',
        'migration:run',
        '--',
        '-d',
        './src/database/datasources/PostgresDataSource.ts',
      ]
    links:
      - database
    depends_on:
      - database
    environment:
      - DB_HOST=database_application

volumes:
  pgdata:
    driver: local
